//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLIDE
    {
        public int ID { get; set; }
        public string TIEU_DE { get; set; }
        public string LINK { get; set; }
        public string IMAGES { get; set; }
        public Nullable<byte> STT { get; set; }
        public Nullable<bool> TRANG_THAI { get; set; }
        public Nullable<bool> NOI_BAT { get; set; }
        public Nullable<System.DateTime> NGAY_DANG { get; set; }
        public Nullable<bool> IS_REMOVE { get; set; }
    }
}
