//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCv1.Models
{
    using System;
    
    public partial class spDanhSachCv_Result1
    {
        public string TenNhaCungCap { get; set; }
        public int ID { get; set; }
        public string TenCongViec { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<double> LuongBatDau { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> LoaiIdCv { get; set; }
        public Nullable<int> ID_TrangThai { get; set; }
        public string LoaiCV { get; set; }
        public Nullable<int> ID_STT { get; set; }
        public string Loai_Trang_Thai { get; set; }
    }
}
